apiVersion: v1
kind: Service
metadata:
  name: admin-dashboard-nodeport
  namespace: dryfruit
spec:
  selector:
    app: admin-dashboard
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 32080
  type: NodePort